name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npx tsc

      - name: Docker build
        run: |
          docker build \
            -f Dockerfile \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/ft_transcendence_be:latest \
            .

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ft_transcendence_be:latest

  deploy-to-ec2:
    needs: docker-build-and-push
    runs-on: self-hosted

    steps:
      - name: Docker pull from Docker Hub
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ft_transcendence_be:latest

      - name: Stop and remove existing container
        run: |
          sudo docker stop ft_transcendence || true
          sudo docker rm ft_transcendence   || true

      - name: Run new container
        run: |
          sudo docker run --name ft_transcendence --rm -d \
            -p 8083:8083 \
            -v "$HOME/ft_transcendence_db:/app/prisma/data" \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            -e ENCRYPTION_KEY="${{ secrets.ENCRYPTION_KEY }}" \
            -e ADMIN_PASSWORD="${{ secrets.ADMIN_PASSWORD }}" \
            -e GOOGLE_CLIENT_EMAIL="${{ secrets.GOOGLE_CLIENT_EMAIL }}" \
            -e "GOOGLE_PRIVATE_KEY=${{ secrets.GOOGLE_PRIVATE_KEY }}" \
            -e GDRIVE_FOLDER_ID="${{ secrets.GDRIVE_FOLDER_ID }}" \
            ${{ secrets.DOCKERHUB_USERNAME }}/ft_transcendence_be:latest
          sleep 5
          sudo docker ps -a

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if schema.prisma changed
        id: prisma
        run: |
          git fetch origin main
          if git diff --name-only origin/main | grep -q 'prisma/schema.prisma'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Run migration if schema.prisma changed
        if: steps.prisma.outputs.changed == 'true'
        run: sudo docker exec ft_transcendence npx prisma migrate deploy

      - name: Check Docker logs
        run: sudo docker logs ft_transcendence || true

      - name: Delete old docker image
        run: sudo docker system prune -f
